import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {forecast,suggestOrder,safeCsv,invoiceDedupe,schemas,signedAmount} from '../lib/domain.ts';
import type {Count} from '../lib/domain.ts';
import {normalizeCounts,normalizeFinances,parseInvoiceText} from '../lib/imports.ts';
const start='2026-09-10';
function history():Count[]{return Array.from({length:56},(_,i)=>{const d=new Date(Date.parse(start+'T12:00:00Z')-(i+1)*864e5);return {id:String(i),date:d.toISOString().slice(0,10),location:'balbin',pan:d.getUTCDay()===6?200:100,papas:10,carne80:120,carne55:null,flags:[],sourceRow:i+3,valid:true}})}
test('pedido con estacionalidad semanal, margen de seguridad y bultos',()=>{const f=forecast(history(),'balbin','pan',7,start);assert.equal(f.reliable,true);assert.equal(f.demand,800);assert.equal(suggestOrder(f.demand,100,20,60,15),840);assert.equal(suggestOrder(100,200,0,30,15),0)});
test('faltantes, historial viejo, duplicados y otro local no producen sugerencia',()=>{assert.equal(forecast(history(),'peron','pan',7,start).demand,null);assert.equal(forecast(history(),'balbin','carne55',7,start).demand,null);assert.equal(forecast(history().slice(0,10),'balbin','pan',7,start).demand,null);assert.equal(forecast(history(),'balbin','pan',7,'2026-12-10').demand,null);assert.equal(forecast([...history(),...history()],'balbin','pan',7,start).demand,null);assert.equal(suggestOrder(100,null,0,10,10),null)});
test('cero explícito válido y no se imputa a faltantes',()=>{const h=history().map(r=>({...r,pan:0}));assert.equal(forecast(h,'balbin','pan',7,start).demand,0);h[0].pan=null as unknown as number;assert.equal(forecast(h,'balbin','pan',7,start).observations,55)});
test('importa celdas numéricas, notas y fechas sin convertir blancos a cero',()=>{const r=normalizeCounts([[],[],[46270,100,'',60,0],[46271,200,20,300,5,'?'],[46272]],'balbin');assert.equal(r.length,2);assert.equal(r[0].papas,null);assert.equal(r[0].carne55,0);assert.equal(r[1].valid,false)});
test('OCR de comprobante argentino deja campos no encontrados en blanco',()=>{assert.deepEqual(parseInvoiceText('CUIT: 30-12345678-9\nFecha: 01/09/2026\n0001-00001234\nImporte total: $ 123.456,78'),{cuit:'30123456789',date:'2026-09-01',number:'00001-00001234',amount:123456.78});assert.equal(parseInvoiceText('Sin importe legible').amount,null)});
test('deduplicación normaliza el punto de venta y las notas de crédito restan',()=>{assert.equal(invoiceDedupe({cuit:'30123456789',documentType:'Factura A',number:'0001-00001234'}),invoiceDedupe({cuit:'30123456789',documentType:'Factura A',number:'00001-00001234'}));assert.equal(signedAmount({documentType:'Nota de crédito A',amount:100}),-100)});
test('validación rechaza fechas imposibles, números e importes inválidos',()=>{assert.equal(schemas.sale.safeParse({location:'balbin',date:'2026-02-30',channel:'Mercado Pago',amount:100}).success,false);assert.equal(schemas.stock.safeParse({location:'balbin',sku:'pan',quantity:-1,countedAt:new Date().toISOString()}).success,false);assert.equal(schemas.invoice.safeParse({location:'balbin',supplier:'Test',cuit:'1',number:'ABC',documentType:'Factura A',date:'2026-09-01',category:'Mercadería',amount:100}).success,false)});
test('export CSV protege fórmulas de texto y conserva los créditos como números',()=>{assert.equal(safeCsv([['=1+1','x;y','a"b']]),'\uFEFF"\'=1+1";"x;y";"a""b"');assert.equal(safeCsv([[-1250,'-1+2']]),'\uFEFF"-1250";"\'-1+2"')});
test('el importador de Sheets concilia julio y conserva agosto incompleto',()=>{const fixture=JSON.parse(readFileSync(new URL('../tests/fixtures/eerr.json',import.meta.url),'utf8'));const parsed=normalizeFinances(fixture);assert.equal(parsed.length,4);const july=parsed.filter(f=>f.period==='2026-07');assert.ok(july.every(f=>f.complete),JSON.stringify(july.map(f=>f.flags)));assert.equal(july.find(f=>f.location==='balbin')!.revenue,85915742);assert.ok(parsed.filter(f=>f.period==='2026-08').every(f=>!f.complete&&f.profit===null))});
